### ISSUE TITLE
Is it working with angular2 rc5?

### ISSUE THREAD

**Issue by Ks89** [brinkmanjg/ng2-typeahead#9]
Is it working with angular2 rc5?

Thank you.

**Comment by andismith** [comment]
RC5 introduces ngModules, so it looks like you need to do two things to get this working:

* move your import statement to be inside your ngModule rather than within the component itself.
* remove the directive from your component and instead include it as a declaration within the ngModule.

If you need to upgrade your code, there is a guide here:
https://angular.io/docs/ts/latest/cookbook/rc4-to-rc5.html

And more about ngModules here:
https://angular.io/docs/ts/latest/guide/ngmodule.html

**Comment by brinkmanjg** [comment]
The component has been updated to work with Angular 2.0.0 (GA), which is the recommended version.
